import Head from "next/head";
import Filter from "../components/Filter";
import Header from "../components/Header";
import HomePageSlider from "../components/HomePageSlider";
import RecentlyViewed from "../components/RecentlyViewed";

export default function Home() {
  return (
    <div className="grid grid-cols-12">
      <Head>
        <title>Go Together</title>
        <meta name="description" content="Generated by Go Together" />
        <link rel="icon" href="/11.png" />
      </Head>
      <div className="col-span-2"></div>
      <div className="col-span-8 space-y-3 bg-slate-100">
        <div>
          <Header />
          <Filter />
        </div>
        <div className="px-5 space-y-3">
          <HomePageSlider />
          <RecentlyViewed />
        </div>
      </div>
      <div className="col-span-2"></div>
    </div>
  );
}
