import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/login'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-black">

      <Head>
        <title>Go Together</title>
        <meta name="description" content="Generated by Go Together" />
        <link rel="icon" href="/11.png" />
      </Head>
      <div className="text-white text-8xl bg-black">ass</div>
      <Login />

    </div>
  )
}
